version: "2"

run:
  timeout: 5m
  tests: false

issues:
  exclude-dirs:
    - build
    - internal/tray
    - hotkeys
  exclude-rules:
    - path: cmd/daemon/main\.go
      text: "error obtaining VCS status"
      linters:
        - typecheck

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
