version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - build
    - build/whisper.cpp

issues:
  exclude-rules:
    - path: cmd/speak-to-ai/main\.go
      text: "error obtaining VCS status"
      linters:
        - typecheck

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosec
    - unconvert
    - unused
    - unparam
