version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - build
    - build/whisper.cpp

issues:
  exclude:
    - "error obtaining VCS status"
    - "Use -buildvcs=false to disable VCS stamping"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosec
    - unconvert
    - unused
    - unparam
