# Speak to AI - Configuration File

# General settings
general:
  debug: false
  model_path: "sources/language-models/base.bin"  # Backward compatibility
  temp_audio_path: "/tmp"
  model_precision: "base"
  language: "auto"  # Auto-detect language, or specify "en", etc.
  log_file: "logs/speak-to-ai.log"  # Log file path (empty to disable file logging)
  
  # Multiple models configuration
  models:
    - "sources/language-models/base.bin"     # Standard quality, balanced speed/accuracy
    - "sources/language-models/small.bin"    # Better quality, slower
    - "sources/language-models/tiny.bin"     # Fastest, lower quality
  active_model: "sources/language-models/base.bin"  # Currently active model

# Hotkey settings
hotkeys:
  start_recording: "ctrl+alt+r"       # Universal default
  stop_recording: "ctrl+alt+r"        # Same combination for start/stop
  switch_model: "altgr+shift+m"        # Switch between models
  # toggle_vad: "altgr+shift+v"          # Toggle VAD on/off
  show_config: "altgr+shift+c"         # Open configuration file
  reset_to_defaults: "altgr+shift+r"   # Reset all settings to defaults

# Audio recording settings
audio:
  device: "default"
  sample_rate: 16000            # Optimal for speech recognition (do not change)
  format: "s16le"               # Note: audio is always recorded in mono (1 channel)
  recording_method: "arecord"   # Options: "arecord", "ffmpeg"
  # TODO: Next feature - VAD implementation
  # enable_vad: false           # Enable Voice Activity Detection
  # vad_sensitivity: "medium"   # VAD sensitivity: "low", "medium", "high"
  # auto_start_stop: false      # Auto start/stop recording based on VAD

# Text output settings
output:
  default_mode: "active_window"  # Options: "clipboard", "active_window", "web" - Fixed: was clipboard
  clipboard_tool: "auto"  # Options: "auto", "wl-copy", "xclip"
  type_tool: "auto"  # Options: "auto", "xdotool", "wl-clipboard", "dbus"

# Web server settings
web_server:
  enabled: false  # Disabled by default - enable only if needed
  port: 8080
  host: "localhost" 