blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/AshBuk/speak-to-ai/blob/master/README.md
    about: Read the documentation and setup guides
  - name: 🚀 Development Guide
    url: https://github.com/AshBuk/speak-to-ai/blob/master/DEVELOPMENT.md
    about: Learn how to build and contribute to the project