name: Build Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: '0.1.0'

permissions:
  contents: write
  actions: read

jobs:
  build-appimage:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Debug - Show environment
      run: |
        echo "=== Environment Debug ==="
        echo "Go version: $(go version)"
        echo "Working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Go mod contents:"
        cat go.mod
        echo "========================"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xclip \
          wl-clipboard \
          libnotify-bin \
          libasound2-dev \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libayatana-appindicator3-dev \
          libgtk-3-dev \
          libglib2.0-dev \
          libdbus-1-dev \
          libdbus-glib-1-dev \
          ffmpeg \
          alsa-utils \
          wget \
          build-essential \
          pkg-config \
          cmake \
          valgrind
          
    - name: Debug - Test Go build
      run: |
        echo "=== Testing Go Build with Systray ==="
        go mod tidy
        echo "Building application with systray support..."
        go build -tags systray -v -o speak-to-ai cmd/daemon/main.go
        echo "Build successful, binary info:"
        ls -la speak-to-ai
        file speak-to-ai
        echo "========================"
          
    - name: Download Whisper model if not present
      run: |
        if [ ! -f "sources/language-models/base.bin" ]; then
          echo "Downloading Whisper base model..."
          mkdir -p sources/language-models
          wget -q "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin" \
            -O "sources/language-models/base.bin"
          echo "Model downloaded, size: $(ls -lh sources/language-models/base.bin)"
        fi
        
    - name: Build Whisper.cpp if not present
      run: |
        if [ ! -f "sources/core/whisper" ] || [ ! -f "sources/core/quantize" ]; then
          echo "Building Whisper.cpp with static linking..."
          mkdir -p sources/core
          git clone https://github.com/ggerganov/whisper.cpp.git /tmp/whisper-cpp
          cd /tmp/whisper-cpp
          # Build with static linking to avoid dynamic library dependencies
          mkdir build
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" -DBUILD_SHARED_LIBS=OFF
          cmake --build build --config Release -j$(nproc)
          echo "Whisper.cpp built, copying binaries..."
          cp build/bin/whisper-cli ${{ github.workspace }}/sources/core/whisper
          cp build/bin/quantize ${{ github.workspace }}/sources/core/quantize
          echo "Binaries copied:"
          ls -la ${{ github.workspace }}/sources/core/
          echo "Checking dependencies:"
          ldd ${{ github.workspace }}/sources/core/whisper || echo "Static binary (no dependencies)"
        fi
        
    - name: Debug - Pre-build status
      run: |
        echo "=== Pre-build Debug ==="
        echo "Sources structure:"
        find sources -type f -exec ls -la {} \;
        echo "AppImage script exists:"
        ls -la bash-scripts/build-appimage.sh
        echo "========================"
        
    - name: Build AppImage
      run: |
        chmod +x bash-scripts/build-appimage.sh
        bash -x bash-scripts/build-appimage.sh
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: speak-to-ai-appimage
        path: |
          dist/*.AppImage
          !dist/tools/
        
  build-flatpak:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      
    - name: Debug - Show environment
      run: |
        echo "=== Flatpak Environment Debug ==="
        echo "Working directory: $(pwd)"
        echo "Flatpak manifest exists:"
        ls -la io.github.ashbuk.speak-to-ai.json
        echo "Flatpak script exists:"
        ls -la bash-scripts/build-flatpak.sh
        echo "========================"
      
    - name: Install Flatpak and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          flatpak \
          flatpak-builder \
          cmake \
          build-essential \
          libayatana-appindicator3-dev \
          libgtk-3-dev \
          libglib2.0-dev \
          libdbus-1-dev \
          libdbus-glib-1-dev \
          ninja-build \
          autotools-dev \
          automake \
          autoconf \
          libtool \
          valgrind
        # Use user remote instead of system remote
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --user -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
        flatpak install --user -y flathub org.freedesktop.Sdk.Extension.golang//23.08
        
    - name: Download Whisper model if not present
      run: |
        if [ ! -f "sources/language-models/base.bin" ]; then
          echo "Downloading Whisper base model..."
          mkdir -p sources/language-models
          wget -q "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin" \
            -O "sources/language-models/base.bin"
        fi
        
    - name: Build Whisper.cpp if not present
      run: |
        if [ ! -f "sources/core/whisper" ] || [ ! -f "sources/core/quantize" ]; then
          echo "Building Whisper.cpp with static linking..."
          mkdir -p sources/core
          git clone https://github.com/ggerganov/whisper.cpp.git /tmp/whisper-cpp
          cd /tmp/whisper-cpp
          # Build with static linking to avoid dynamic library dependencies
          mkdir build
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" -DBUILD_SHARED_LIBS=OFF
          cmake --build build --config Release -j$(nproc)
          cp build/bin/whisper-cli ${{ github.workspace }}/sources/core/whisper
          cp build/bin/quantize ${{ github.workspace }}/sources/core/quantize
          echo "Checking dependencies:"
          ldd ${{ github.workspace }}/sources/core/whisper || echo "Static binary (no dependencies)"
        fi
        
    - name: Pre-download Go modules for Flatpak
      run: |
        echo "Pre-downloading Go modules..."
        go mod download
        go mod verify
        
    - name: Fix SHA256 for libayatana-ido
      run: |
        # Download and get correct SHA256
        TEMP_DIR=$(mktemp -d)
        cd $TEMP_DIR
        wget -q https://github.com/AyatanaIndicators/libayatana-ido/archive/refs/tags/0.10.4.tar.gz
        CORRECT_SHA=$(sha256sum 0.10.4.tar.gz | cut -d' ' -f1)
        cd $GITHUB_WORKSPACE
        rm -rf $TEMP_DIR
        
        # Update manifest with correct SHA256
        sed -i "s/fb3b3b7d3b0c4a3b9f0b2c2e9f2b1c1b4c9f5e3f5e9b2e3c2e9f2b1c1b4c9f5/$CORRECT_SHA/g" io.github.ashbuk.speak-to-ai.json
        
    - name: Build Flatpak package
      run: |
        mkdir -p dist/flatpak
        
        # Build with dependencies
        flatpak-builder \
          --force-clean \
          --user \
          --install-deps-from=flathub \
          --install-deps-only \
          --ccache \
          --repo=dist/flatpak/repo \
          dist/flatpak/build-dir \
          io.github.ashbuk.speak-to-ai.json
          
        # Build the actual package
        flatpak-builder \
          --force-clean \
          --user \
          --ccache \
          --repo=dist/flatpak/repo \
          dist/flatpak/build-dir \
          io.github.ashbuk.speak-to-ai.json
          
    - name: Create flatpak bundle
      run: |
        flatpak build-bundle \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          dist/flatpak/repo \
          dist/io.github.ashbuk.speak-to-ai.flatpak \
          io.github.ashbuk.speak-to-ai
        
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: speak-to-ai-flatpak
        path: dist/io.github.ashbuk.speak-to-ai.flatpak
        
  create-release:
    needs: [build-appimage, build-flatpak]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download AppImage artifact
      uses: actions/download-artifact@v4
      with:
        name: speak-to-ai-appimage
        path: ./artifacts/
        
    - name: Download Flatpak artifact
      uses: actions/download-artifact@v4
      with:
        name: speak-to-ai-flatpak
        path: ./artifacts/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/*.AppImage
          ./artifacts/*.flatpak
        body: |
          ## Speak-to-AI Release ${{ github.ref_name }}
          
          ### Features:
          - 🎤 Offline speech-to-text using Whisper.cpp
          - 🔧 System tray integration with recording status
          - ⌨️ Microsoft Copilot key support (AltGr + ,)
          - 📋 Multiple output modes: clipboard, direct typing
          - 🖥️ Cross-platform support for X11 and Wayland
          - 🔒 Privacy-first: no data sent to external servers
          
          ### Installation:
          
          **AppImage:**
          ```bash
          chmod +x speak-to-ai-*.AppImage
          ./speak-to-ai-*.AppImage
          ```
          
          **Flatpak:**
          ```bash
          flatpak install speak-to-ai-*.flatpak
          flatpak run io.github.ashbuk.speak-to-ai
          ```
          
          ### System Requirements:
          - Linux (Ubuntu 20.04+, Fedora 35+, or similar)
          - X11 or Wayland desktop environment
          - Audio recording capability (microphone)
          - ~200MB disk space for model and dependencies
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 