name: Test Build

on:
  push:
    branches: [ main, develop, test-build-fix ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-compilation:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libayatana-appindicator3-dev \
          libgtk-3-dev \
          libglib2.0-dev \
          libdbus-1-dev \
          pkg-config \
          build-essential
        
    - name: Test Go modules
      run: |
        echo "Testing Go modules..."
        go mod tidy
        go mod verify
        
    - name: Test basic compilation
      run: |
        echo "Testing basic compilation..."
        go build -v -o test-basic cmd/daemon/main.go
        ls -la test-basic
        
    - name: Test systray compilation
      run: |
        echo "Testing systray compilation..."
        go build -tags systray -v -o test-systray cmd/daemon/main.go
        ls -la test-systray
        
    - name: Test configuration loading
      run: |
        echo "Testing configuration loading..."
        go run cmd/daemon/main.go --help || echo "Help command completed"
        
    - name: Run unit tests
      run: |
        echo "Running unit tests..."
        go test -v ./...
        
    - name: Check project structure
      run: |
        echo "Checking project structure..."
        echo "✅ Flatpak manifest:" && ls -la io.github.ashbuk.speak-to-ai.json
        echo "✅ Wrapper script:" && ls -la flatpak-wrapper.sh
        echo "✅ Build scripts:" && ls -la bash-scripts/
        echo "✅ Configuration:" && ls -la config.yaml
        echo "✅ Desktop file:" && ls -la io.github.ashbuk.speak-to-ai.desktop
        echo "✅ AppData file:" && ls -la io.github.ashbuk.speak-to-ai.appdata.xml
        
    - name: Validate desktop file
      run: |
        echo "Validating desktop file..."
        sudo apt-get install -y desktop-file-utils
        desktop-file-validate io.github.ashbuk.speak-to-ai.desktop
        
    - name: Test local dependencies check
      run: |
        echo "Testing local dependencies check..."
        chmod +x bash-scripts/build-flatpak.sh
        bash bash-scripts/build-flatpak.sh --help 