name: Test AppImage Only

on:
  push:
    tags:
      - 'v*-appimage-test'

permissions:
  contents: write
  actions: read

jobs:
  build-appimage:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Debug - Show environment
      run: |
        echo "=== Environment Debug ==="
        echo "Go version: $(go version)"
        echo "Working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Go mod contents:"
        cat go.mod
        echo "========================"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xclip \
          wl-clipboard \
          libnotify-bin \
          libasound2-dev \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          ffmpeg \
          alsa-utils \
          wget \
          build-essential \
          pkg-config \
          cmake
          
    - name: Debug - Test Go build
      run: |
        echo "=== Testing Go Build ==="
        go mod tidy
        echo "Building application..."
        go build -v -o speak-to-ai cmd/daemon/main.go
        echo "Build successful, binary info:"
        ls -la speak-to-ai
        file speak-to-ai
        echo "========================"
          
    - name: Download Whisper model if not present
      run: |
        if [ ! -f "sources/language-models/base.bin" ]; then
          echo "Downloading Whisper base model..."
          mkdir -p sources/language-models
          wget -q "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin" \
            -O "sources/language-models/base.bin"
          echo "Model downloaded, size: $(ls -lh sources/language-models/base.bin)"
        fi
        
    - name: Build Whisper.cpp if not present
      run: |
        if [ ! -f "sources/core/whisper" ] || [ ! -f "sources/core/quantize" ]; then
          echo "Building Whisper.cpp with static linking..."
          mkdir -p sources/core
          git clone https://github.com/ggerganov/whisper.cpp.git /tmp/whisper-cpp
          cd /tmp/whisper-cpp
          # Build with static linking to avoid dynamic library dependencies
          mkdir build
          cmake -B build -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" -DBUILD_SHARED_LIBS=OFF
          cmake --build build --config Release -j$(nproc)
          echo "Whisper.cpp built, copying binaries..."
          cp build/bin/whisper-cli ${{ github.workspace }}/sources/core/whisper
          cp build/bin/quantize ${{ github.workspace }}/sources/core/quantize
          echo "Binaries copied:"
          ls -la ${{ github.workspace }}/sources/core/
          echo "Checking dependencies:"
          ldd ${{ github.workspace }}/sources/core/whisper || echo "Static binary (no dependencies)"
        fi
        
    - name: Debug - Pre-build status
      run: |
        echo "=== Pre-build Debug ==="
        echo "Sources structure:"
        find sources -type f -exec ls -la {} \;
        echo "AppImage script exists:"
        ls -la bash-scripts/build-appimage.sh
        echo "========================"
        
    - name: Build AppImage
      run: |
        chmod +x bash-scripts/build-appimage.sh
        bash -x bash-scripts/build-appimage.sh
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: speak-to-ai-appimage
        path: dist/*.AppImage
        
    - name: Create Release (AppImage only)
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.AppImage
        body: |
          ## Speak-to-AI AppImage Test Release ${{ github.ref_name }}
          
          ### Test AppImage Build
          - 🎤 Offline speech-to-text using Whisper.cpp
          - 🔧 System tray integration with recording status
          - ⌨️ Microsoft Copilot key support (AltGr + ,)
          - 📋 Multiple output modes: clipboard, direct typing
          - 🖥️ Cross-platform support for X11 and Wayland
          - 🔒 Privacy-first: no data sent to external servers
          
          ### Installation:
          ```bash
          chmod +x speak-to-ai-*.AppImage
          ./speak-to-ai-*.AppImage
          ```
          
        draft: false
        prerelease: true
        fail_on_unmatched_files: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 